export const GeneralList = [
  {
    name: "Eugene of Savoy",
    listOfBattle: [
      "Battle of Vienna",
      "Siege of Buda (1684)",
      "Siege of Buda (1686)",
      "Battle of Mohács",
      "Siege of Belgrade",
      "Battle of Zenta",
      "Sack of Sarajevo",
      "Battle of Staffarda",
      "Battle of Carpi",
      "Battle of Chiari",
      ,
      "Battle of Cremona",
      "Battle of Luzzara",
      "Battle of Blenheim",
      "Battle of Cassano",
      "Siege of Turin",
      "Battle of Toulon",
      "Battle of Oudenarde",
      "Siege of Lille",
      "Crossing of the Scheldt",
      "Battle of Malplaquet",
      "Battle of Denain",
      "Rhine campaign (1713)",
      "Battle of Petrovaradin",
      "Siege of Temeşvar",
      "Battle of Belgrade",
      "Siege of Philippsburg",
    ],

    rank: "Generalfeldmarschall of Holy Roman Empire",
  },
];
